### ISSUE TITLE
Chapter 4 Problem | No vertex array object bound.

### ISSUE THREAD

**Issue by gitvika** [lwjglgamedev/lwjglbook#82] opened 2020-05-26 00:17 UTC
This is the error I get after finishing Chapter 4, with the exact same code as the book:
**Error validating shader code: Specified type - Validation Failed: No vertex array object bound.**
I've done the code the exact same way as you did for Chapter 4 (which amazing explanation by the way), any idea why it's not validating? No errors or nothing.

**Comment by lwjglgamedev** [comment] 2020-05-26 06:17
Hi,

Two suggestions:
- Make sure your GPU drivers are updated.
- Comment the validation lines 59 to 62. To check if the program works. The glValidateProgram check if the shader is correct with the current OpenGL context. Maybe this is not strictly true when the shader is created but may be ok when the shader is executed later on. Your driver may be doing extra validations that are not done in my setup.

Let me know if this helps.

**Comment by gitvika** [comment] 2020-05-26 13:48
> Hi,
> 
> Two suggestions:
> 
> * Make sure your GPU drivers are updated.
> * Comment the validation lines 59 to 62. To check if the program works. The glValidateProgram check if the shader is correct with the current OpenGL context. Maybe this is not strictly true when the shader is created but may be ok when the shader is executed later on. Your driver may be doing extra validations that are not done in my setup.
> 
> Let me know if this helps.

I'm not very sure this may also affect to this, however, I'm on a MacBook.

**Comment by lwjglgamedev** [comment] 2020-05-26 17:40
It should work on Mac too. Unfortunately I don't have a Mac to test with. Please try what I suggest and come back with the results.

**Comment by gitvika** [comment] 2020-05-26 19:24
> It should work on Mac too. Unfortunately I don't have a Mac to test with. Please try what I suggest and come back with the results.

Okay, changed it and now it doesn't show the triangle, however, there are no more errors.

**Comment by neomonkeus** [comment] 2020-05-26 22:17
I am seeing this error also on mac. 

I only really noticed it as chapter05/c02-2 it actually didn't display the same error but I think that is a separate issue as it is calling different logs method `glGetShaderInfoLog` vs `glGetProgramInfoLog`
```
glValidateProgram(programId);
if (glGetProgrami(programId, GL_VALIDATE_STATUS) == 0){
    System.err.println("Warning validating Shader code: " + glGetShaderInfoLog(programId, 1024));
}

if (glGetProgrami(programId, GL_VALIDATE_STATUS) == 0) {
    System.err.println("Warning validating Program code: " + glGetProgramInfoLog(programId, 1024));
}
```
That prints the following 
```
Warning validating Shader code: 
Warning validating Program code: Validation Failed: No vertex array object bound.
```

Looking at your suggestions about time of validation, I also threw in validation when the VAO was bound and the original error disappeared.
```
        // Draw the mesh
        glBindVertexArray(mesh.getVaoId());
        validate(shaderProgram.getId());

        glDrawElements(GL_TRIANGLES, mesh.getVertexCount(), GL_UNSIGNED_INT, 0);

        // Restore state
        glBindVertexArray(0);

        shaderProgram.unbind();
    }

    private void validate(int programId) {
        glValidateProgram(programId);
        if (glGetProgrami(programId, GL_VALIDATE_STATUS) == 0){
            System.err.println("Warning validating Shader code: " + glGetShaderInfoLog(programId, 1024));
        }
        if (glGetProgrami(programId, GL_VALIDATE_STATUS) == 0) {
            System.err.println("Warning validating Program code: " + glGetProgramInfoLog(programId, 1024));
        }
    }
```

**Comment by gitvika** [comment] 2020-05-27 02:14
> I am seeing this error also on mac.
> 
> I only really noticed it as chapter05/c02-2 it actually didn't display the same error but I think that is a separate issue as it is calling different logs method `glGetShaderInfoLog` vs `glGetProgramInfoLog`
> 
> ```
> glValidateProgram(programId);
> if (glGetProgrami(programId, GL_VALIDATE_STATUS) == 0){
>     System.err.println("Warning validating Shader code: " + glGetShaderInfoLog(programId, 1024));
> }
> 
> if (glGetProgrami(programId, GL_VALIDATE_STATUS) == 0) {
>     System.err.println("Warning validating Program code: " + glGetProgramInfoLog(programId, 1024));
> }
> ```
> 
> That prints the following
> 
> ```
> Warning validating Shader code: 
> Warning validating Program code: Validation Failed: No vertex array object bound.
> ```
> 
> Looking at your suggestions about time of validation, I also threw in validation when the VAO was bound and the original error disappeared.
> 
> ```
>         // Draw the mesh
>         glBindVertexArray(mesh.getVaoId());
>         validate(shaderProgram.getId());
> 
>         glDrawElements(GL_TRIANGLES, mesh.getVertexCount(), GL_UNSIGNED_INT, 0);
> 
>         // Restore state
>         glBindVertexArray(0);
> 
>         shaderProgram.unbind();
>     }
> 
>     private void validate(int programId) {
>         glValidateProgram(programId);
>         if (glGetProgrami(programId, GL_VALIDATE_STATUS) == 0){
>             System.err.println("Warning validating Shader code: " + glGetShaderInfoLog(programId, 1024));
>         }
>         if (glGetProgrami(programId, GL_VALIDATE_STATUS) == 0) {
>             System.err.println("Warning validating Program code: " + glGetProgramInfoLog(programId, 1024));
>         }
>     }
> ```

Now its just Error validating shader code: Specified type -

**Comment by lwjglgamedev** [comment] 2020-05-27 06:24
Thanks for commenting.

@neomonkeus Are you using and old version of the samples source code ? The messages are different in latest version.

@gitvika In any case, it seems that the VAO is not bound indeed. Are you sure you are not modyfing the source code or the shaders ? Have you checked your drivers also?

In any case you could try to enable debug mode by passing the argument '-Dorg.lwjgl.util.Debug=true' to the JVM as explained here: https://github.com/LWJGL/lwjgl3-wiki/wiki/2.5.-Troubleshooting

Please check what it returns and paste it here.

It's very difficult for me to track this issues since I cannot test them. I gues I should get a Mac 😄

**Comment by gitvika** [comment] 2020-05-27 12:54
> Thanks for commenting.
> 
> @neomonkeus Are you using and old version of the samples source code ? The messages are different in latest version.
> 
> @gitvika In any case, it seems that the VAO is not bound indeed. Are you sure you are not modyfing the source code or the shaders ? Have you checked your drivers also?
> 
> In any case you could try to enable debug mode by passing the argument '-Dorg.lwjgl.util.Debug=true' to the JVM as explained here: https://github.com/LWJGL/lwjgl3-wiki/wiki/2.5.-Troubleshooting
> 
> Please check what it returns and paste it here.
> 
> It's very difficult for me to track this issues since I cannot test them. I gues I should get a Mac 😄

You could get a virtual machine, it works and operates the same.

**Comment by gitvika** [comment] 2020-05-27 13:10
> Thanks for commenting.
> 
> @neomonkeus Are you using and old version of the samples source code ? The messages are different in latest version.
> 
> @gitvika In any case, it seems that the VAO is not bound indeed. Are you sure you are not modyfing the source code or the shaders ? Have you checked your drivers also?
> 
> In any case you could try to enable debug mode by passing the argument '-Dorg.lwjgl.util.Debug=true' to the JVM as explained here: https://github.com/LWJGL/lwjgl3-wiki/wiki/2.5.-Troubleshooting
> 
> Please check what it returns and paste it here.
> 
> It's very difficult for me to track this issues since I cannot test them. I gues I should get a Mac 😄

I got it working! I for some reason wrote it all over from chapter 5, and sure enough, it worked. however, still getting the error about validating the shader code, but it rendered the colours.

**Comment by lwjglgamedev** [comment] 2020-05-27 13:29
Great !

Now it makes sense to me. I will probably delete the validation code since it may cause issues. Please, leave this issue open. I will come back with a decission on the solution and will close it accordingly.

Thanks for pointing this.

**Comment by gitvika** [comment] 2020-05-27 14:37
> Great !
> 
> Now it makes sense to me. I will probably delete the validation code since it may cause issues. Please, leave this issue open. I will come back with a decission on the solution and will close it accordingly.
> 
> Thanks for pointing this.

Remember, you should get VirtualBox with MacOS and openSuse and Kali. That way, you can work on them whenever you may post a new chapter or somebody needs help with other operating systems. You're definitely going to get credit on my game, cause you're amazing.

**Comment by lwjglgamedev** [comment] 2020-05-27 18:11
Thanks for your comment and your advice. The issue is that, last time I checked VirtualBox did not support OpenGL. I will check again.

At the end, Reviewing the book chapter I think it's explained what the function does, so I opt by know to leave it as it is. So I close the issue.

Best regards.

**Comment by gitvika** [comment] 2020-05-27 18:12
> > Great !
> > Now it makes sense to me. I will probably delete the validation code since it may cause issues. Please, leave this issue open. I will come back with a decission on the solution and will close it accordingly.
> > Thanks for pointing this.
> 
> Remember, you should get VirtualBox with MacOS and openSuse or Kali. That way, you can work on them whenever you may post a new chapter or somebody needs help with other operating systems. You're definitely going to get credit on my game, cause you're amazing.

Sorry for doing this again, however, I have two things:
When following the "Textures" chapter, it says it can't find textures/grassblock.png. However, do I create a new source folder or just a regular folder for this part? Cause it seems its just that.

**Closed by lwjglgamedev** 2020-05-27 18:11 UTC

**Comment by gitvika** [comment] 2020-05-27 18:16
Fixed it, source folder.
